[project]
name = "visualization"
version = "10.1.0"
description = "Visualization tools for image processing benchmarks"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "matplotlib-stubs>=0.3.11",
    "pandas>=2.3.3",
    "pandas-stubs>=2.3.3.251219",
    "pyrefly>=0.46.1",
    "seaborn>=0.13.2",
    "types-seaborn>=0.13.2.20251221",
]

[tool.pyrefly]
project-includes = ["**/*.py*", "**/*.ipynb"]

[tool]
